// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAqqlrFIs07g01qf6XNIPI7gqeD5rV41A',
    appId: '1:637965316799:web:40f62cee0d4df629ad4c0a',
    messagingSenderId: '637965316799',
    projectId: 'beritaku-32bd2',
    authDomain: 'beritaku-32bd2.firebaseapp.com',
    storageBucket: 'beritaku-32bd2.firebasestorage.app',
    measurementId: 'G-4TBMN5VJCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFeNpPCFKfvegtzwGGrkHh0fs08CALsIw',
    appId: '1:637965316799:android:a94955b38d4abb49ad4c0a',
    messagingSenderId: '637965316799',
    projectId: 'beritaku-32bd2',
    storageBucket: 'beritaku-32bd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1fAwTVWL8-fTHXH-77vG71vu-4kWSZU',
    appId: '1:637965316799:ios:32ede99665d251e5ad4c0a',
    messagingSenderId: '637965316799',
    projectId: 'beritaku-32bd2',
    storageBucket: 'beritaku-32bd2.firebasestorage.app',
    iosBundleId: 'com.example.beritaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf1fAwTVWL8-fTHXH-77vG71vu-4kWSZU',
    appId: '1:637965316799:ios:32ede99665d251e5ad4c0a',
    messagingSenderId: '637965316799',
    projectId: 'beritaku-32bd2',
    storageBucket: 'beritaku-32bd2.firebasestorage.app',
    iosBundleId: 'com.example.beritaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAqqlrFIs07g01qf6XNIPI7gqeD5rV41A',
    appId: '1:637965316799:web:52198dbf2e8bb40cad4c0a',
    messagingSenderId: '637965316799',
    projectId: 'beritaku-32bd2',
    authDomain: 'beritaku-32bd2.firebaseapp.com',
    storageBucket: 'beritaku-32bd2.firebasestorage.app',
    measurementId: 'G-R6NQ0CGJGF',
  );
}
